#!/usr/bin/env bash
#
# Push the server-side secrets this app needs into Vercel.
#
# Four features are built, tested and deployed but dark in production, because
# the deployment cannot reach Supabase:
#
#   - the freshness panel in the header
#   - the canonical store and the projection history on the player page
#   - the daily refresh cron
#   - /api/refresh
#
# They need three variables. This reads them from your local .env.local — which
# already has two of them — generates the third, and pushes all three to the
# linked Vercel project.
#
# Run it yourself. The values never leave your machine except to go to your own
# Vercel account, and nothing here prints a secret to the terminal.
#
#     bash scripts/setup-vercel-env.sh
#
# Idempotent: an existing variable is removed and re-added rather than
# duplicated, so re-running it is safe and is also how you rotate a value.

set -euo pipefail

cd "$(dirname "$0")/.."

if [[ ! -f .env.local ]]; then
  echo "error: .env.local not found. Copy .env.example and fill it in first." >&2
  exit 1
fi

if [[ ! -f .vercel/project.json ]]; then
  echo "error: this directory is not linked to a Vercel project. Run: npx vercel link" >&2
  exit 1
fi

# Read a value out of .env.local without sourcing the file, so a stray line in
# there cannot execute anything.
read_env() {
  local key="$1"
  sed -n "s/^${key}=//p" .env.local | head -1 | sed 's/^"//;s/"$//'
}

SUPABASE_URL="$(read_env NEXT_PUBLIC_SUPABASE_URL)"
SUPABASE_KEY="$(read_env SUPABASE_SECRET_KEY)"
CRON="$(read_env CRON_SECRET)"

missing=()
[[ -z "$SUPABASE_URL" ]] && missing+=("NEXT_PUBLIC_SUPABASE_URL")
[[ -z "$SUPABASE_KEY" ]] && missing+=("SUPABASE_SECRET_KEY")

if (( ${#missing[@]} > 0 )); then
  echo "error: missing from .env.local: ${missing[*]}" >&2
  exit 1
fi

# CRON_SECRET is not a credential you hold anywhere — it is a shared token that
# only has to match between Vercel Cron and the route. Generated if absent, and
# written back so the local .env.local and production agree.
if [[ -z "$CRON" ]]; then
  CRON="$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64url"))')"
  printf '\n# Generated by scripts/setup-vercel-env.sh — must match Vercel.\nCRON_SECRET=%s\n' "$CRON" >> .env.local
  echo "generated CRON_SECRET and appended it to .env.local"
fi

push() {
  local key="$1" value="$2"
  for env in production preview development; do
    # Remove first so a re-run replaces rather than erroring on a duplicate.
    npx --yes vercel env rm "$key" "$env" --yes >/dev/null 2>&1 || true
    printf '%s' "$value" | npx --yes vercel env add "$key" "$env" >/dev/null 2>&1
  done
  echo "  set $key"
}

echo "pushing to Vercel (production, preview, development):"
push NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
push SUPABASE_SECRET_KEY "$SUPABASE_KEY"
push CRON_SECRET "$CRON"

echo
echo "done. Redeploy for them to take effect:"
echo "    npx vercel --prod"
echo
echo "then check:  curl -s https://fantasy-football-edge.vercel.app/api/data-status | head -c 400"
echo "the header should read 'Data ...' rather than 'Data unknown'."
