#!/usr/bin/env bash
#
# Push the server-side secrets this app needs into Vercel.
#
# Four features are built, tested and deployed but dark in production, because
# the deployment cannot reach Supabase:
#
#   - the freshness panel in the header
#   - the canonical store and the projection history on the player page
#   - the daily refresh cron
#   - /api/refresh
#
# They need three variables. This reads them from your local .env.local — which
# already has two of them — generates the third, and pushes all three to the
# linked Vercel project.
#
# Run it yourself. The values never leave your machine except to go to your own
# Vercel account, and nothing here prints a secret to the terminal.
#
#     bash scripts/setup-vercel-env.sh --dry-run   # show what it would do
#     bash scripts/setup-vercel-env.sh             # do it
#
# Idempotent: an existing variable is removed and re-added rather than
# duplicated, so re-running it is safe and is also how you rotate a value.

set -euo pipefail

cd "$(dirname "$0")/.."

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

if [[ ! -f .env.local ]]; then
  echo "error: .env.local not found. Copy .env.example and fill it in first." >&2
  exit 1
fi

if [[ ! -f .vercel/project.json ]]; then
  echo "error: this directory is not linked to a Vercel project. Run: npx vercel link" >&2
  exit 1
fi

# Read a value out of .env.local without sourcing the file, so a stray line in
# there cannot execute anything.
read_env() {
  local key="$1"
  sed -n "s/^${key}=//p" .env.local | head -1 | sed 's/^"//;s/"$//'
}

SUPABASE_URL="$(read_env NEXT_PUBLIC_SUPABASE_URL)"
SUPABASE_KEY="$(read_env SUPABASE_SECRET_KEY)"
CRON="$(read_env CRON_SECRET)"

missing=()
[[ -z "$SUPABASE_URL" ]] && missing+=("NEXT_PUBLIC_SUPABASE_URL")
[[ -z "$SUPABASE_KEY" ]] && missing+=("SUPABASE_SECRET_KEY")

if (( ${#missing[@]} > 0 )); then
  echo "error: missing from .env.local: ${missing[*]}" >&2
  exit 1
fi

# CRON_SECRET is not a credential you hold anywhere — it is a shared token that
# only has to match between Vercel Cron and the route. Generated if absent, and
# written back so the local .env.local and production agree.
if [[ -z "$CRON" ]]; then
  CRON="$(node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("base64url"))')"
  printf '\n# Generated by scripts/setup-vercel-env.sh — must match Vercel.\nCRON_SECRET=%s\n' "$CRON" >> .env.local
  echo "generated CRON_SECRET and appended it to .env.local"
fi

# Resolve the CLI once.
#
# The first version called `npx vercel` for every operation — three variables x
# three environments x two commands is eighteen invocations, each re-resolving
# the package. With output suppressed that looked like a hang: the header
# printed and then nothing moved for over a minute. Resolving once makes it
# quick, and printing per environment makes it visibly alive.
VERCEL="$(command -v vercel || true)"
if [[ -z "$VERCEL" ]]; then
  echo "resolving vercel CLI..."
  npx --yes vercel --version >/dev/null 2>&1
  VERCEL="npx --yes vercel"
fi

push() {
  local key="$1" value="$2"

  # `NEXT_PUBLIC_*` is inlined into the browser bundle by the framework, so it
  # is public by construction and Vercel refuses to store it with secret
  # visibility on Production or Preview. That refusal is correct — marking it
  # secret would be theatre, not security. The two values that ARE secret keep
  # the default sensitive visibility.
  #
  # A plain string, not an array. macOS ships bash 3.2, where expanding an
  # EMPTY array as "${flags[@]}" trips `set -u` with "unbound variable" — so the
  # array version worked for the one key that needed a flag and blew up on the
  # two that did not. The flag here is a fixed literal, so word-splitting an
  # unquoted string is safe.
  local flags=""
  if [[ "$key" == NEXT_PUBLIC_* ]]; then
    flags="--no-sensitive"
  fi

  if (( DRY_RUN )); then
    # Length only. Enough to confirm the right value was found, useless to
    # anyone reading over a shoulder or scrolling back through a terminal.
    echo "  would set $key (${#value} chars) in production, preview, development"
    return
  fi

  printf '  %s' "$key"
  for env in production preview development; do
    # Remove first so a re-run replaces rather than erroring on a duplicate.
    # Errors here are expected when the variable does not exist yet.
    $VERCEL env rm "$key" "$env" --yes >/dev/null 2>&1 || true
    : >/tmp/ffe-env-add.log

    # Failures here are NOT expected, and the first version swallowed them:
    # `set -e` killed the script mid-run with the output redirected to
    # /dev/null, so it exited silently having done part of the job. Captured
    # and reported instead.
    if ! printf '%s' "$value" | $VERCEL env add "$key" "$env" $flags >/tmp/ffe-env-add.log 2>&1; then
      echo " — FAILED on $env"
      echo "vercel said:" >&2
      tail -5 /tmp/ffe-env-add.log >&2
      exit 1
    fi
    printf ' %s' "$env"
  done
  echo " ✓"
}

if (( DRY_RUN )); then
  echo "dry run — nothing will be sent:"
else
  echo "pushing to Vercel (production, preview, development):"
fi
push NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
push SUPABASE_SECRET_KEY "$SUPABASE_KEY"
push CRON_SECRET "$CRON"

if (( DRY_RUN )); then
  echo
  echo "dry run complete. Re-run without --dry-run to apply."
  exit 0
fi

echo
echo "done. Redeploy for them to take effect:"
echo "    npx vercel --prod"
echo
echo "then check:  curl -s https://fantasy-football-edge.vercel.app/api/data-status | head -c 400"
echo "the header should read 'Data ...' rather than 'Data unknown'."
